//Workspaces
export const RECEIVE_WORKSPACES = 'RECEIVE_WORKSPACES';
export const RECEIVE_TAGS = 'RECEIVE_TAGS';
export const RECEIVE_BUNDLES = 'RECEIVE_BUNDLES';
export const RECEIVE_GROUPS = 'RECEIVE_GROUPS';
export const RECEIVE_MACHINE_NAMES = 'RECEIVE_MACHINE_NAMES';
export const RECEIVE_USER_NAMES = 'RECEIVE_USER_NAMES';

//Search filter
export const UPDATE_SEARCH_GROUP = 'UPDATE_SEARCH_GROUP'
export const UPDATE_USER_NAMES = 'UPDATE_USER_NAMES'
